-- SPECIALISATIONS -------------------------------------------------
DROP table SPECIALISATIONS;
CREATE TABLE SPECIALISATIONS (
  id   NUMBER        NOT NULL PRIMARY KEY ,
  name VARCHAR2 (20) NOT NULL
);

DROP SEQUENCE SPECIALISATIONS_seq;
CREATE SEQUENCE SPECIALISATIONS_seq START WITH 1;
CREATE OR REPLACE TRIGGER spec_autoincrement
  BEFORE INSERT ON SPECIALISATIONS
  FOR EACH ROW
  BEGIN
    SELECT SPECIALISATIONS_seq.NEXTVAL
    INTO   :new.id
    FROM   dual;
  END;

INSERT INTO SPECIALISATIONS (name) VALUES ('Computer Science');
INSERT INTO SPECIALISATIONS (name) VALUES ('Geology');
INSERT INTO SPECIALISATIONS (name) VALUES ('Mathematics');
INSERT INTO SPECIALISATIONS (name) VALUES ('Physics');
COMMIT;
